'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const loadTs = require('./load-ts.cjs');
const { parseTranscript } = loadTs('src/main/officeChat.ts');

const row = (o) => JSON.stringify(o);
const user = (content, extra = {}) => row({ type: 'user', uuid: `u${Math.random()}`, timestamp: '2026-10-09T10:00:00.000Z', message: { role: 'user', content }, ...extra });
const asst = (blocks, extra = {}) => row({ type: 'assistant', uuid: `a${Math.random()}`, timestamp: '2026-10-09T10:00:05.000Z', message: { role: 'assistant', content: blocks }, ...extra });

test('user prompts and assistant text become bubbles, in order', () => {
  const lines = parseTranscript([
    user('fix the login bug'),
    asst([{ type: 'text', text: 'On it.' }]),
    asst([{ type: 'text', text: 'Done — see the diff.' }]),
  ].join('\n'));
  assert.deepEqual(lines.map((l) => [l.role, l.text]), [
    ['user', 'fix the login bug'], ['agent', 'On it.'], ['agent', 'Done — see the diff.'],
  ]);
  assert.equal(lines[0].ts, Date.parse('2026-10-09T10:00:00.000Z'));
});

test('tools, thinking, tool results and empty turns never show', () => {
  const lines = parseTranscript([
    asst([{ type: 'thinking', thinking: 'hmm' }, { type: 'tool_use', name: 'Bash', input: {} }]),
    user([{ type: 'tool_result', tool_use_id: 'x', content: 'ok' }]),
    asst([{ type: 'text', text: 'Ran it.' }, { type: 'tool_use', name: 'Read', input: {} }]),
  ].join('\n'));
  assert.deepEqual(lines.map((l) => l.text), ['Ran it.']);
});

test('harness-injected user turns, sidechains and meta rows are skipped', () => {
  const lines = parseTranscript([
    user('<system-reminder>be careful</system-reminder>'),
    user('<command-name>/clear</command-name>'),
    user('Caveat: The messages below were generated by the user'),
    user('sub-agent chatter', { isSidechain: true }),
    user('meta', { isMeta: true }),
    user('a real question'),
  ].join('\n'));
  assert.deepEqual(lines.map((l) => l.text), ['a real question']);
});

test('torn lines, junk and missing fields are tolerated; limit keeps the newest', () => {
  const body = ['{"type":"user","message":{"content":"par', 'not json', row({ type: 'summary' }), user('one'), user('two'), user('three')].join('\n');
  assert.deepEqual(parseTranscript(body, 2).map((l) => l.text), ['two', 'three']);
  assert.deepEqual(parseTranscript(''), []);
});
